Use the version of OPM based on the ocp version label of the index
release-engineering/iib pull request #145
Opened 2020-09-03 12:35 UTC by shawn-hurley

* opm now must be installed to opmv4.5 and opmv4.6
* added tests to make sure that OCP_VERSION label was respected

2020-09-03 13:09 UTC, lcarva commented
Should we have a mechanism for setting up a default binary? Maybe that's not necessary. 

Let's have the corresponding changes in the [dev environment|https://github.com/release-engineering/iib/blob/master/docker/Dockerfile-workers] though. Otherwise, it'll break.

2020-09-03 13:23 UTC, lipoja requested changes

2020-09-03 13:23 UTC, lipoja commented on iib/workers/tasks/build.py
> +    base_dir, bundles, binary_image, ocp_version, from_index=None, overwrite_from_index_token=None
Could you add docstring for this parameter? 
Thank you!

2020-09-03 13:23 UTC, lipoja commented on iib/workers/tasks/build.py
> +    base_dir, operators, binary_image, from_index, ocp_version, overwrite_from_index_token=None
Could you add docstring for this parameter as well?
Thank you!

2020-09-03 13:23 UTC, lipoja commented on iib/workers/tasks/build.py
> +def _opm_index_rm(
Could you please update a call of this function (on line 870). Otherwise a wrong value is passed to the `ocp_version` parameter.
Thank you.

2020-09-07 07:11 UTC, querti commented
May I ask the reason for needing both versions? Do they have different functionality?

2020-09-18 18:35 UTC, yashvardhannanavati approved these changes

2020-09-21 06:32 UTC, querti requested changes
With new merged changes, it also has to be changed in the registry serve command

2020-09-28 19:36 UTC, shawn-hurley commented
Closing this PR for now. I believe that we may want to come back and do this but we should not add this right now.

2020-09-28 19:36 UTC, closed without merging