Remove the support of privileged users
release-engineering/iib pull request #249
Opened 2021-05-13 03:25 UTC by emilyzheng

For all users, overwriting index image is only allowed when overwrite_from_index/overwrite_target_index is True and overwrite_from_index_token/overwrite_target_index_token is set.

2021-05-13 04:53 UTC, emilyzheng commented
@yashvardhannanavati Could you help to add reviewers?

2021-05-19 13:19 UTC, lipoja approved these changes

2021-05-24 09:01 UTC, pbortlov commented
I am wondering if this branch is rebased with the newest upstream/master it seems that you are deleting functions from build.py which is not in the scope of this PR.

2021-05-24 09:02 UTC, pbortlov requested changes

2021-05-24 09:02 UTC, pbortlov commented on iib/workers/tasks/build.py
> -def _get_image_arches(pull_spec):
This is not in the scope of this PR

2021-05-24 12:25 UTC, pbortlov approved these changes

2021-05-24 21:23 UTC, yashvardhannanavati approved these changes

2021-05-27 15:29 UTC, merged